import 'package:get/get.dart';

class LocalLocalizations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "add_category": "Add Category",
          "recent_activities": "Recent Activities",
          "Enter_UserName": "Enter the Username",
          "Search_by_platform": "Search by platform",
          "Send_Message": "Send Message",
          "Hire_Me": "Hire Me",
          "Projects_Completed": "Campaign Completed",
          "About_Me": "About Me",
          "My_Portfolio": "My Portfolio",
          "Search_Links": "Search Links",
          "Ongoing_Projects": "Ongoing Campaign",
          "Recent_Task": "Recent Phase",
          "All_Projects": "All Campaign",
          "No_in_progress_projects_found": "No in-progress campaign found",
          "Edit_Profile": "Edit Profile",
          "Upload_Project": "Media Upload",
          "Notifications": "Notifications",
          "No_Completed_Projects": "No Completed campaign",
          "Greeting_Message": "Hello {name}",
          "Account_type": "Account Type",
          "Let's_Personalize_Your_Journey!": "Let's Personalize Your Journey!",
          "Customize_your_experience_by_selecting_the_role_that_suits_your_best":
              "Customize your experience by selecting the role that suits your best",
          "Join_as_brand": "Join as brand",
          "Join_as_Influencer": "Join as Content creator",
          "Continue": "Continue",
          "Login_to_your_account": "Login to your account",
          "Hi!_Welcome_back_you_have_been_missed":
              "Hi! Welcome back you have been missed",
          "Enter_your_Email": "Enter Your Email",
          "Your_password": "Your password",
          "Remember_me": "Remember me",
          "Forgot_password": "Forgot Password",
          "Sign_In": "Sign In",
          "Don't_Have_an_Account?": "Don't Have an Account?",
          "Or": "Or",
          "Sign_up": "Sign up",
          "Create_Account": "Create Account",
          "Fill_Your_Information_below_or_register_with_your_social_media":
              "Fill Your Information below or register with your social media",
          "Create_passowrd": "Create passowrd",
          "Confirm _Passowrd": "Confirm_Passowrd",
          "Sign_Up": "Sign Up",
          "Already_have_an_Account?": "Already have an Account",
          "Login": "Login",
          "Good_morning!": "Good morning!",
          "Hello": "Hello",
          "Featured_Influencers": "Featured Content creators",
          "Complete": "Complete",
          "Rating": "Rating",
          "Search_by_category": "Search by category",
          "Recommended_for_you": "Recommended for you",
          "Search_by_paltform": "Search by paltform",
          "Home": "Home",
          "Project": "Campaign",
          "Message": "Message",
          "Profile": "profile",
          "Ongoing_Project": "Ongoing Campaign",
          "View_more": "View more",
          "Progress": "Progress",
          "Tasks": "Tasks",
          "Backlog": "Backlog",
          "In_progress": "In Progress",
          "Completed": "Completed",
          "Messages": "Messages",
          "Personal_Info": "Personal Info",
          "My_Profile": "My profile",
          "My_Payment": "My Payment",
          "Security": "Security",
          "Change_Password": "Change Passowrd",
          "You_will_receive_passowrd_reset_instruction_via_email":
              "You will receive passowrd reset instruction via_email",
          "Send_Recovery_link": "Send Recovery link",
          "New_passowrd": "New Passowrd",
          "Confirm_new_Passowrd": "Confirm new Passowrd",
          "There_must_be_at_least_8_charecters":
              "There must be at least 8 charecters",
          "There_must_be_a_unique_code_like_@!#":
              "There must be a unique code like @!#",
          "Passsword_Change_Successfully": "Passsword Change Successfully",
          "Congratulations!_You_have_changed_your_passowrd_successfully":
              "Congratulations! You have changed your passowrd successfully",
          "Suggested_Language": "Suggested Language",
          "My_Payments": "My_Payments",
          "Personal_Information": "Personal Information",
          "Profile_Complete": "Profile Complete",
          "Company_Deatils": "Company Deatils",
          "Name": "Name",
          "Username": "Username",
          "Bio": "Bio",
          "Awards": "Awards",
          "Add New": "Add New",
          "Social_Links": "Social Links",
          "Facebook": "Facebook",
          "Instragram": "Instragram",
          "TikTok": "TikTok",
          "Youtube": "Youtube",
          "Add_New_Award": "Add New Award",
          "Enter_award_title": "Enter award title",
          "Add_your_bio": "Add your bio",
          "Search..,": "Search...",
          "Create_New_Project": "Create New Project",
          "Project_title": "Project_title",
          "Enter_task_title": "Enter task title",
          "Description": "Description",
          "Enter_task_description": "Enter task description",
          "Start_date": "Start Date",
          "Due_date": "Due Date",
          "Select_start_date_and_time": "Select start date and time",
          "Select_due_date_and_time": "Select due date and time",
          "Price": "Price",
          "Add_Project_File": "Add Project File",
          "Add_necessary_document_for_this_project":
              "Add necessary document for this project",
          "Optional": "Optional",
          "Ok": "Ok",
          "Cancel": "Cancel",
          "Project_Successful": "Project Successful",
          "Wait_for_the_person_you_invited_to_reply_to_you":
              "Wait for the person you invited to reply to you",
          "We'll_let_you_know_right_away": "We'll let you know right away",
          "View_project": "View project",
          "Project_Details": " Details",
          "Read_more": "Read more",
          "Add_New_Task": "Add New Task",
          "Project_Task": "Project Task",
          "Create_Sub_Task": "Create Sub Task",
          "Task_title": "Task title",
          "Priority": "Priority",
          "Low": "Low",
          "Medium": "Medium",
          "High": "High",
          "Submit": "Submit",
          "Arabic": "Arabic",
          "Settings": "Settings",
          "Language": "Language",
          "Support_&_Legal": "Support & Legal",
          "Log_Out": "Log Out",
          "Company_Personal_Information": "Company Personal Information",
          "Profile_Related_Data": "Profile Related Data",
          "Update_Company_Name": "Update Company Name",
          "Change_Company_Name": "Change Company Name",
          "Company_Location": "Company Location",
          "Company_Name": "Company Name",
          "Company_Username": "Company Username",
          "Update_Personal_Information": "Update Personal Information",
          "Company_Bio": "Company Bio",
          "Enter_company_bio": "Enter company bio",
          "Company_Awards": "Company Awards",
          "Add_New": "Add New",
          "Instagram": "Instagram",
          "YouTube": "YouTube",
          "Update_Information": "Update Information",
          "Choose_category": "Choose category",
          "Enter_company_name": "Enter company name",
          "A_special_character_(@,_!,_#,_etc.)":
              "A special character (@, !, #, etc.)",
          "At_least_8_characters": "At least 8 characters",
          "New_Password": "New Password",
          "Old_Password": "Old Password",
          "Enter_the_old_password_and_the_new_password":
              "Enter the old password and the new password",
          "Support_Message":
              "For any support-related inquiries, please reach out to us at 'support@example.com' or call us at '+123-456-7890'. We are here to help you 24/7.",
          "Legal": "Legal",
          "Legal_Description":
              "By using our application, you agree to the Terms of Service and Privacy Policy. Please ensure you have read and understood these policies before using the app.",
          "About_Us": "About Us",
          "About_Us_Description":
              "Our mission is to provide the best service to our users. If you have any feedback or suggestions, feel free to contact us.",
          "Search_influencers": "Search Content creator...",
          "In_Progress": "In Progress",
          "No_in-progress_projects_found": "No in-progress Campaign found",
          "Untitled_Task": "Untitled Task",
          "LOW": "LOW",
          "MEDIUM": "MEDIUM",
          "HIGH": "HIGH",
          "days_ago": "days ago",
          "Today": "Today",
          "days_left": "days left",
          "Invalid_date": "Invalid date",
          "In Progress": "In Progress",
          "Goodmorning!": "Good morning!",
          "No_tasks_available": "No tasks available",
          "Forgot_password?": "Forgot password?",
        },
        'ar_AR': {
          "add_category": "أضف فئة",
          "recent_activities": "الأنشطة الأخيرة",
          "enter_Username": "أدخل اسم المستخدم",
          "Forgot_password?": "نسيت كلمة المرور؟",
          "No_tasks_available": "لا توجد مهام متاحة",
          "Goodmorning!": "صباح الخير!",
          "In Progress": "في تَقَدم",
          "Invalid_date": "تاريخ غير صالح",
          "days left": "الأيام المتبقية",
          "Today": "اليوم",
          "days_ago": "منذ أيام",
          "HIGH": "عالي",
          "MEDIUM": "واسطة",
          "LOW": "قليل",
          "Untitled_Task": "مهمة بلا عنوان",
          "No_Completed_Projects": "لا توجد حملة مكتملة",
          "No_in-progress_projects_found":
              "لم يتم العثور على أي حملة قيد التقدم ",
          "In_Progress": "في تَقَدم",
          "Notifications": "الإشعارات",
          "Edit_Profile": "تعديل الملف الشخصي",
          "Upload_Project": "تحميل الوسائط",
          "No_in_progress_projects_found":
              "لم يتم العثور على مشاريع قيد التنفيذ",
          "All_Projects": "جميع المشاريع",
          "Ongoing_Projects": "الحملة مستمرة",
          "Recent_Task": "المهمة الأخيرة",
          "Search_Links": "روابط البحث",
          "About_Me": "عني",
          "My_Portfolio": "ملفي الشخصي",
          "Send_Message": "إرسال رسالة",
          "Hire_Me": "وظفني",
          "Projects_Completed": "المشاريع المنجزة",
          "Greeting_Message": "مرحبًا {name}",
          "Search_by_platform": "البحث حسب المنصة",
          "Search_influencers": "ابحث عن المؤثرين...",
          "Support_Message":
              "لأي استفسارات متعلقة بالدعم، يرجى التواصل معنا عبر 'support@example.com' أو الاتصال بنا على '+123-456-7890'. نحن هنا لمساعدتك على مدار الساعة.",
          "Legal": "قانوني",
          "Legal_Description":
              "باستخدام تطبيقنا، فإنك توافق على شروط الخدمة وسياسة الخصوصية. يرجى التأكد من قراءة وفهم هذه السياسات قبل استخدام التطبيق.",
          "About_Us": "معلومات عنا",
          "About_Us_Description":
              "مهمتنا هي تقديم أفضل خدمة لمستخدمينا. إذا كان لديك أي تعليقات أو اقتراحات، فلا تتردد في الاتصال بنا.",
          "A_special_character_(@,_!,_#,_etc.)": "حرف خاص (@، !، #، إلخ)",
          "At_least_8_characters": "على الأقل 8 أحرف",
          "New_Password": "كلمة مرور جديدة",
          "Old_Password": "كلمة المرور القديمة",
          "Enter_the_old_password_and_the_new_password":
              "أدخل كلمة المرور القديمة وكلمة المرور الجديدة",
          "Update_Information": "تحديث المعلومات",
          "Choose_category": "اختر الفئة",
          "Enter_company_name": "أدخل اسم الشركة",
          "Company_Location": "موقع الشركة",
          "Company_Personal_Information": "معلومات شخصية عن الشركة",
          "Profile_Related_Data": "بيانات ذات صلة بالملف الشخصي",
          "Update_Company_Name": "تحديث اسم الشركة",
          "Change_Company_Name": "تغيير اسم الشركة",
          "Company_Name": "اسم الشركة",
          "Company_Username": "اسم المستخدم للشركة",
          "Update_Personal_Information": "تحديث المعلومات الشخصية",
          "Company_Bio": "السيرة الذاتية للشركة",
          "Enter_company_bio": "أدخل السيرة الذاتية للشركة",
          "Company_Awards": "جوائز الشركة",
          "Add_New": "إضافة جديد",
          "Add_New_Award": "إضافة جائزة جديدة",
          "Enter_award_title": "أدخل عنوان الجائزة",
          "Submit": "إرسال",
          "Account_type": "نوع الحساب",
          "My_Payments": "مدفوعاتي",
          "Let's_Personalize_Your_Journey!": "لنقم بتخصيص رحلتك!",
          "Customize_your_experience_by_selecting_the_role_that_suits_your_best":
              "قم بتخصيص تجربتك عن طريق اختيار الدور الذي يناسبك أكثر",
          "Join_as_brand": "انضم كعلامة تجارية",
          "Join_as_Influencer": "انضم كمؤثر",
          "Continue": "متابعة",
          "Login_to_your_account": "تسجيل الدخول إلى حسابك",
          "Hi!_Welcome_back_you_have_been_missed":
              "مرحبًا! أهلاً بعودتك، لقد اشتقنا إليك",
          "Enter_your_Email": "أدخل بريدك الإلكتروني",
          "Your_password": "كلمة المرور الخاصة بك",
          "Remember_me": "تذكرني",
          "Forgot_password": "نسيت كلمة المرور",
          "Sign_In": "تسجيل الدخول",
          "Don't_Have_an_Account?": "ليس لديك حساب؟",
          "Or": "أو",
          "Sign_up": "إنشاء حساب",
          "Create_Account": "إنشاء حساب",
          "Fill_Your_Information_below_or_register_with_your_social_media":
              "املأ معلوماتك أدناه أو قم بالتسجيل باستخدام وسائل التواصل الاجتماعي",
          "Create_passowrd": "إنشاء كلمة مرور",
          "Confirm _Passowrd": "تأكيد كلمة المرور",
          "Sign_Up": "تسجيل",
          "Already_have_an_Account?": "هل لديك حساب بالفعل؟",
          "Login": "تسجيل الدخول",
          "Good_morning!": "صباح الخير!",
          "Hello": "مرحبًا",
          "Featured_Influencers": "المؤثرون المميزون",
          "Complete": "اكتمل",
          "Rating": "التقييم",
          "Search_by_category": "بحث حسب الفئة",
          "Recommended_for_you": "موصى به لك",
          "Search_by_paltform": "بحث حسب المنصة",
          "Home": "الصفحة الرئيسية",
          "Campaign": "حملة",
          "Project": "المشروع",
          "Message": "الرسالة",
          "Profile": "الملف الشخصي",
          "Ongoing_Project": "مشروع قيد التنفيذ",
          "View_more": "عرض المزيد",
          "Progress": "التقدم",
          "Tasks": "المهام",
          "Backlog": "التراكم",
          "In_progress": "قيد التنفيذ",
          "Completed": "مكتمل",
          "Messages": "الرسائل",
          "Personal_Info": "المعلومات الشخصية",
          "My_Profile": "ملفي الشخصي",
          "My_Payment": "مدفوعاتي",
          "Security": "الأمان",
          "Change_Password": "تغيير كلمة المرور",
          "You_will_receive_passowrd_reset_instruction_via_email":
              "ستتلقى تعليمات إعادة تعيين كلمة المرور عبر البريد الإلكتروني",
          "Send_Recovery_link": "إرسال رابط الاسترداد",
          "New_passowrd": "كلمة مرور جديدة",
          "Confirm_new_Passowrd": "تأكيد كلمة المرور الجديدة",
          "There_must_be_at_least_8_charecters":
              "يجب أن تكون هناك 8 أحرف على الأقل",
          "There_must_be_a_unique_code_like_@!#":
              "يجب أن يكون هناك رمز فريد مثل @!#",
          "Passsword_Change_Successfully": "تم تغيير كلمة المرور بنجاح",
          "Congratulations!_You_have_changed_your_passowrd_successfully":
              "تهانينا! لقد قمت بتغيير كلمة المرور بنجاح",
          "Suggested_Language": "اللغة المقترحة",
          "Personal_Information": "المعلومات الشخصية",
          "Profile_Complete": "اكتمل الملف الشخصي",
          "Company_Deatils": "تفاصيل الشركة",
          "Name": "الاسم",
          "Username": "اسم المستخدم",
          "Bio": "السيرة الذاتية",
          "Awards": "الجوائز",
          "Add New": "إضافة جديد",
          "Social_Links": "روابط التواصل الاجتماعي",
          "Facebook": "فيسبوك",
          "Instagram": "إنستغرام",
          "TikTok": "تيك توك",
          "YouTube": "يوتيوب",
          "Add_your_bio": "أضف سيرتك الذاتية",
          "Search..,": "بحث...",
          "Create_New_Project": "إنشاء مشروع جديد",
          "Project_title": "عنوان المشروع",
          "Enter_task_title": "أدخل عنوان المهمة",
          "Description": "الوصف",
          "Enter_task_description": "أدخل وصف المهمة",
          "Start_date": "تاريخ البدء",
          "Due_date": "تاريخ الانتهاء",
          "Select_start_date_and_time": "حدد تاريخ ووقت البدء",
          "Select_due_date_and_time": "حدد تاريخ ووقت الانتهاء",
          "Price": "السعر",
          "Add_Project_File": "إضافة ملف المشروع",
          "Add_necessary_document_for_this_project":
              "إضافة المستندات اللازمة لهذا المشروع",
          "Optional": "اختياري",
          "Ok": "موافق",
          "Cancel": "إلغاء",
          "Project_Successful": "تم المشروع بنجاح",
          "Wait_for_the_person_you_invited_to_reply_to_you":
              "انتظر رد الشخص الذي دعوتَه",
          "We'll_let_you_know_right_away": "سنخبرك فورًا",
          "View_project": "عرض المشروع",
          "Project_Details": "تفاصيل المشروع",
          "Read_more": "قراءة المزيد",
          "Add_New_Task": "إضافة مهمة جديدة",
          "Project_Task": "مهام المشروع",
          "Create_Sub_Task": "إنشاء مهمة فرعية",
          "Task_title": "عنوان المهمة",
          "Priority": "الأولوية",
          "Low": "منخفض",
          "Medium": "متوسط",
          "High": "عالي",
          "Arabic": "العربية",
          "Settings": "الإعدادات",
          "Language": "اللغة",
          "Support_&_Legal": "الدعم والقانوني",
          "Log_Out": "تسجيل الخروج"
        }
      };
}
